// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using World.Data;

#nullable disable

namespace World.Migrations
{
    [DbContext(typeof(WorldContext))]
    partial class WorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("World.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 50.850299999999997,
                            Longitude = 4.3517000000000001,
                            Name = "Brussels",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 51.2194,
                            Longitude = 4.4024999999999999,
                            Name = "Antwerp",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "Paris",
                            StateId = 2
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 45.764000000000003,
                            Longitude = 4.8357000000000001,
                            Name = "Lyon",
                            StateId = 2
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 34.052199999999999,
                            Longitude = -118.2437,
                            Name = "Los Angeles",
                            StateId = 3
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 37.774900000000002,
                            Longitude = -122.4194,
                            Name = "San Francisco",
                            StateId = 3
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 52.520000000000003,
                            Longitude = 13.404999999999999,
                            Name = "Berlin",
                            StateId = 4
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 5,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 40.416800000000002,
                            Longitude = -3.7038000000000002,
                            Name = "Madrid",
                            StateId = 5
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 6,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            Name = "Rome",
                            StateId = 6
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 7,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 35.689500000000002,
                            Longitude = 139.6917,
                            Name = "Tokyo",
                            StateId = 7
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 8,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -33.8688,
                            Longitude = 151.20930000000001,
                            Name = "Sydney",
                            StateId = 8
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 9,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -23.5505,
                            Longitude = -46.633299999999998,
                            Name = "São Paulo",
                            StateId = 9
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 10,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 51.507199999999997,
                            Longitude = -0.12759999999999999,
                            Name = "London",
                            StateId = 10
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 11,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 43.651000000000003,
                            Longitude = -79.346999999999994,
                            Name = "Toronto",
                            StateId = 11
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 12,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -33.924900000000001,
                            Longitude = 18.424099999999999,
                            Name = "Cape Town",
                            StateId = 12
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 13,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 28.613900000000001,
                            Longitude = 77.209000000000003,
                            Name = "New Delhi",
                            StateId = 13
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 51.054299999999998,
                            Longitude = 3.7174,
                            Name = "Ghent",
                            StateId = 1
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 43.7102,
                            Longitude = 7.2619999999999996,
                            Name = "Nice",
                            StateId = 2
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 3,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 32.715699999999998,
                            Longitude = -117.1611,
                            Name = "San Diego",
                            StateId = 3
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 4,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 53.551099999999998,
                            Longitude = 9.9937000000000005,
                            Name = "Hamburg",
                            StateId = 4
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 41.385100000000001,
                            Longitude = 2.1734,
                            Name = "Barcelona",
                            StateId = 5
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 6,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 45.464199999999998,
                            Longitude = 9.1899999999999995,
                            Name = "Milan",
                            StateId = 6
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 7,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 34.6937,
                            Longitude = 135.50229999999999,
                            Name = "Osaka",
                            StateId = 7
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 8,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -37.813600000000001,
                            Longitude = 144.9631,
                            Name = "Melbourne",
                            StateId = 8
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 9,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -22.9068,
                            Longitude = -43.172899999999998,
                            Name = "Rio de Janeiro",
                            StateId = 9
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 10,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 52.486199999999997,
                            Longitude = -1.8904000000000001,
                            Name = "Birmingham",
                            StateId = 10
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 11,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 49.282699999999998,
                            Longitude = -123.1207,
                            Name = "Vancouver",
                            StateId = 11
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 12,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = -29.858699999999999,
                            Longitude = 31.021799999999999,
                            Name = "Durban",
                            StateId = 12
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 13,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 19.076000000000001,
                            Longitude = 72.877700000000004,
                            Name = "Mumbai",
                            StateId = 13
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 1,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 50.632599999999996,
                            Longitude = 5.5796999999999999,
                            Name = "Liège",
                            StateId = 1
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 2,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 43.604700000000001,
                            Longitude = 1.4441999999999999,
                            Name = "Toulouse",
                            StateId = 2
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 3,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 38.581600000000002,
                            Longitude = -121.4944,
                            Name = "Sacramento",
                            StateId = 3
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 4,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 48.135100000000001,
                            Longitude = 11.582000000000001,
                            Name = "Munich",
                            StateId = 4
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 5,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 39.469900000000003,
                            Longitude = -0.37630000000000002,
                            Name = "Valencia",
                            StateId = 5
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 6,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 40.851799999999997,
                            Longitude = 14.2681,
                            Name = "Naples",
                            StateId = 6
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 7,
                            CreatedOn = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Latitude = 35.011600000000001,
                            Longitude = 135.7681,
                            Name = "Kyoto",
                            StateId = 7
                        });
                });

            modelBuilder.Entity("World.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capital")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DeclarationOfIndependence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmojiU")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMonarchy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iso2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Native")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumericCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tld")
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capital = "Brussels",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1830, 10, 4),
                            Emoji = "🇧🇪",
                            EmojiU = "U+1F1E7 U+1F1EA",
                            IsMonarchy = true,
                            Iso2 = "BE",
                            Iso3 = "BEL",
                            Latitude = 50.850299999999997,
                            Longitude = 4.3517000000000001,
                            Name = "Belgium",
                            Nationality = "Belgian",
                            Native = "België",
                            NumericCode = "056",
                            PhoneCode = "32",
                            Tld = ".be",
                            WikiDataId = "Q31"
                        },
                        new
                        {
                            Id = 2,
                            Capital = "Paris",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1789, 7, 14),
                            Emoji = "🇫🇷",
                            EmojiU = "U+1F1EB U+1F1F7",
                            IsMonarchy = false,
                            Iso2 = "FR",
                            Iso3 = "FRA",
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "France",
                            Nationality = "French",
                            Native = "France",
                            NumericCode = "250",
                            PhoneCode = "33",
                            Tld = ".fr",
                            WikiDataId = "Q142"
                        },
                        new
                        {
                            Id = 3,
                            Capital = "Washington",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "USD",
                            CurrencyName = "US Dollar",
                            CurrencySymbol = "$",
                            DeclarationOfIndependence = new DateOnly(1776, 7, 4),
                            Emoji = "🇺🇸",
                            EmojiU = "U+1F1FA U+1F1F8",
                            IsMonarchy = false,
                            Iso2 = "US",
                            Iso3 = "USA",
                            Latitude = 38.895099999999999,
                            Longitude = -77.0364,
                            Name = "United States",
                            Nationality = "American",
                            Native = "United States",
                            NumericCode = "840",
                            PhoneCode = "1",
                            Tld = ".us",
                            WikiDataId = "Q30"
                        },
                        new
                        {
                            Id = 4,
                            Capital = "Berlin",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1990, 10, 3),
                            Emoji = "🇩🇪",
                            EmojiU = "U+1F1E9 U+1F1EA",
                            IsMonarchy = false,
                            Iso2 = "DE",
                            Iso3 = "DEU",
                            Latitude = 52.520000000000003,
                            Longitude = 13.404999999999999,
                            Name = "Germany",
                            Nationality = "German",
                            Native = "Deutschland",
                            NumericCode = "276",
                            PhoneCode = "49",
                            Tld = ".de",
                            WikiDataId = "Q183"
                        },
                        new
                        {
                            Id = 5,
                            Capital = "Madrid",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1492, 1, 2),
                            Emoji = "🇪🇸",
                            EmojiU = "U+1F1EA U+1F1F8",
                            IsMonarchy = true,
                            Iso2 = "ES",
                            Iso3 = "ESP",
                            Latitude = 40.416800000000002,
                            Longitude = -3.7038000000000002,
                            Name = "Spain",
                            Nationality = "Spanish",
                            Native = "España",
                            NumericCode = "724",
                            PhoneCode = "34",
                            Tld = ".es",
                            WikiDataId = "Q29"
                        },
                        new
                        {
                            Id = 6,
                            Capital = "Rome",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1861, 3, 17),
                            Emoji = "🇮🇹",
                            EmojiU = "U+1F1EE U+1F1F9",
                            IsMonarchy = false,
                            Iso2 = "IT",
                            Iso3 = "ITA",
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            Name = "Italy",
                            Nationality = "Italian",
                            Native = "Italia",
                            NumericCode = "380",
                            PhoneCode = "39",
                            Tld = ".it",
                            WikiDataId = "Q38"
                        },
                        new
                        {
                            Id = 7,
                            Capital = "Tokyo",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "JPY",
                            CurrencyName = "Yen",
                            CurrencySymbol = "¥",
                            DeclarationOfIndependence = new DateOnly(660, 2, 11),
                            Emoji = "🇯🇵",
                            EmojiU = "U+1F1EF U+1F1F5",
                            IsMonarchy = true,
                            Iso2 = "JP",
                            Iso3 = "JPN",
                            Latitude = 35.676200000000001,
                            Longitude = 139.65029999999999,
                            Name = "Japan",
                            Nationality = "Japanese",
                            Native = "日本",
                            NumericCode = "392",
                            PhoneCode = "81",
                            Tld = ".jp",
                            WikiDataId = "Q17"
                        },
                        new
                        {
                            Id = 8,
                            Capital = "Canberra",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "AUD",
                            CurrencyName = "Australian Dollar",
                            CurrencySymbol = "$",
                            DeclarationOfIndependence = new DateOnly(1901, 1, 1),
                            Emoji = "🇦🇺",
                            EmojiU = "U+1F1E6 U+1F1FA",
                            IsMonarchy = true,
                            Iso2 = "AU",
                            Iso3 = "AUS",
                            Latitude = -35.280900000000003,
                            Longitude = 149.13,
                            Name = "Australia",
                            Nationality = "Australian",
                            Native = "Australia",
                            NumericCode = "036",
                            PhoneCode = "61",
                            Tld = ".au",
                            WikiDataId = "Q408"
                        },
                        new
                        {
                            Id = 9,
                            Capital = "Brasília",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "BRL",
                            CurrencyName = "Brazilian Real",
                            CurrencySymbol = "R$",
                            DeclarationOfIndependence = new DateOnly(1822, 9, 7),
                            Emoji = "🇧🇷",
                            EmojiU = "U+1F1E7 U+1F1F7",
                            IsMonarchy = false,
                            Iso2 = "BR",
                            Iso3 = "BRA",
                            Latitude = -15.826700000000001,
                            Longitude = -47.921799999999998,
                            Name = "Brazil",
                            Nationality = "Brazilian",
                            Native = "Brasil",
                            NumericCode = "076",
                            PhoneCode = "55",
                            Tld = ".br",
                            WikiDataId = "Q155"
                        },
                        new
                        {
                            Id = 10,
                            Capital = "London",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "GBP",
                            CurrencyName = "Pound Sterling",
                            CurrencySymbol = "£",
                            DeclarationOfIndependence = new DateOnly(1707, 5, 1),
                            Emoji = "🇬🇧",
                            EmojiU = "U+1F1EC U+1F1E7",
                            IsMonarchy = true,
                            Iso2 = "GB",
                            Iso3 = "GBR",
                            Latitude = 51.507199999999997,
                            Longitude = -0.12759999999999999,
                            Name = "United Kingdom",
                            Nationality = "British",
                            Native = "United Kingdom",
                            NumericCode = "826",
                            PhoneCode = "44",
                            Tld = ".uk",
                            WikiDataId = "Q145"
                        },
                        new
                        {
                            Id = 11,
                            Capital = "Ottawa",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "CAD",
                            CurrencyName = "Canadian Dollar",
                            CurrencySymbol = "$",
                            DeclarationOfIndependence = new DateOnly(1867, 7, 1),
                            Emoji = "🇨🇦",
                            EmojiU = "U+1F1E8 U+1F1E6",
                            IsMonarchy = true,
                            Iso2 = "CA",
                            Iso3 = "CAN",
                            Latitude = 45.421500000000002,
                            Longitude = -75.697199999999995,
                            Name = "Canada",
                            Nationality = "Canadian",
                            Native = "Canada",
                            NumericCode = "124",
                            PhoneCode = "1",
                            Tld = ".ca",
                            WikiDataId = "Q16"
                        },
                        new
                        {
                            Id = 12,
                            Capital = "Pretoria",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "ZAR",
                            CurrencyName = "South African Rand",
                            CurrencySymbol = "R",
                            DeclarationOfIndependence = new DateOnly(1961, 5, 31),
                            Emoji = "🇿🇦",
                            EmojiU = "U+1F1FF U+1F1E6",
                            IsMonarchy = false,
                            Iso2 = "ZA",
                            Iso3 = "ZAF",
                            Latitude = -25.746099999999998,
                            Longitude = 28.188099999999999,
                            Name = "South Africa",
                            Nationality = "South African",
                            Native = "South Africa",
                            NumericCode = "710",
                            PhoneCode = "27",
                            Tld = ".za",
                            WikiDataId = "Q258"
                        },
                        new
                        {
                            Id = 13,
                            Capital = "New Delhi",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "INR",
                            CurrencyName = "Indian Rupee",
                            CurrencySymbol = "₹",
                            DeclarationOfIndependence = new DateOnly(1947, 8, 15),
                            Emoji = "🇮🇳",
                            EmojiU = "U+1F1EE U+1F1F3",
                            IsMonarchy = false,
                            Iso2 = "IN",
                            Iso3 = "IND",
                            Latitude = 28.613900000000001,
                            Longitude = 77.209000000000003,
                            Name = "India",
                            Nationality = "Indian",
                            Native = "भारत",
                            NumericCode = "356",
                            PhoneCode = "91",
                            Tld = ".in",
                            WikiDataId = "Q668"
                        },
                        new
                        {
                            Id = 14,
                            Capital = "Stockholm",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "SEK",
                            CurrencyName = "Swedish Krona",
                            CurrencySymbol = "kr",
                            DeclarationOfIndependence = new DateOnly(1523, 6, 6),
                            Emoji = "🇸🇪",
                            EmojiU = "U+1F1F8 U+1F1EA",
                            IsMonarchy = true,
                            Iso2 = "SE",
                            Iso3 = "SWE",
                            Latitude = 59.329300000000003,
                            Longitude = 18.0686,
                            Name = "Sweden",
                            Nationality = "Swedish",
                            Native = "Sverige",
                            NumericCode = "752",
                            PhoneCode = "46",
                            Tld = ".se",
                            WikiDataId = "Q34"
                        },
                        new
                        {
                            Id = 15,
                            Capital = "Oslo",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "NOK",
                            CurrencyName = "Norwegian Krone",
                            CurrencySymbol = "kr",
                            DeclarationOfIndependence = new DateOnly(1905, 6, 7),
                            Emoji = "🇳🇴",
                            EmojiU = "U+1F1F3 U+1F1F4",
                            IsMonarchy = true,
                            Iso2 = "NO",
                            Iso3 = "NOR",
                            Latitude = 59.913899999999998,
                            Longitude = 10.7522,
                            Name = "Norway",
                            Nationality = "Norwegian",
                            Native = "Norge",
                            NumericCode = "578",
                            PhoneCode = "47",
                            Tld = ".no",
                            WikiDataId = "Q20"
                        },
                        new
                        {
                            Id = 16,
                            Capital = "Bern",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "CHF",
                            CurrencyName = "Swiss Franc",
                            CurrencySymbol = "Fr",
                            DeclarationOfIndependence = new DateOnly(1291, 8, 1),
                            Emoji = "🇨🇭",
                            EmojiU = "U+1F1E8 U+1F1ED",
                            IsMonarchy = false,
                            Iso2 = "CH",
                            Iso3 = "CHE",
                            Latitude = 46.948099999999997,
                            Longitude = 7.4474,
                            Name = "Switzerland",
                            Nationality = "Swiss",
                            Native = "Schweiz",
                            NumericCode = "756",
                            PhoneCode = "41",
                            Tld = ".ch",
                            WikiDataId = "Q39"
                        },
                        new
                        {
                            Id = 17,
                            Capital = "Amsterdam",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1581, 7, 26),
                            Emoji = "🇳🇱",
                            EmojiU = "U+1F1F3 U+1F1F1",
                            IsMonarchy = true,
                            Iso2 = "NL",
                            Iso3 = "NLD",
                            Latitude = 52.367600000000003,
                            Longitude = 4.9040999999999997,
                            Name = "Netherlands",
                            Nationality = "Dutch",
                            Native = "Nederland",
                            NumericCode = "528",
                            PhoneCode = "31",
                            Tld = ".nl",
                            WikiDataId = "Q55"
                        },
                        new
                        {
                            Id = 18,
                            Capital = "Lisbon",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "EUR",
                            CurrencyName = "Euro",
                            CurrencySymbol = "€",
                            DeclarationOfIndependence = new DateOnly(1143, 10, 5),
                            Emoji = "🇵🇹",
                            EmojiU = "U+1F1F5 U+1F1F9",
                            IsMonarchy = false,
                            Iso2 = "PT",
                            Iso3 = "PRT",
                            Latitude = 38.716900000000003,
                            Longitude = -9.1399000000000008,
                            Name = "Portugal",
                            Nationality = "Portuguese",
                            Native = "Portugal",
                            NumericCode = "620",
                            PhoneCode = "351",
                            Tld = ".pt",
                            WikiDataId = "Q45"
                        },
                        new
                        {
                            Id = 19,
                            Capital = "Mexico City",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "MXN",
                            CurrencyName = "Mexican Peso",
                            CurrencySymbol = "$",
                            DeclarationOfIndependence = new DateOnly(1810, 9, 16),
                            Emoji = "🇲🇽",
                            EmojiU = "U+1F1F2 U+1F1FD",
                            IsMonarchy = false,
                            Iso2 = "MX",
                            Iso3 = "MEX",
                            Latitude = 19.432600000000001,
                            Longitude = -99.133200000000002,
                            Name = "Mexico",
                            Nationality = "Mexican",
                            Native = "México",
                            NumericCode = "484",
                            PhoneCode = "52",
                            Tld = ".mx",
                            WikiDataId = "Q96"
                        },
                        new
                        {
                            Id = 20,
                            Capital = "Beijing",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "CNY",
                            CurrencyName = "Renminbi",
                            CurrencySymbol = "¥",
                            DeclarationOfIndependence = new DateOnly(1949, 10, 1),
                            Emoji = "🇨🇳",
                            EmojiU = "U+1F1E8 U+1F1F3",
                            IsMonarchy = false,
                            Iso2 = "CN",
                            Iso3 = "CHN",
                            Latitude = 39.904200000000003,
                            Longitude = 116.4074,
                            Name = "China",
                            Nationality = "Chinese",
                            Native = "中国",
                            NumericCode = "156",
                            PhoneCode = "86",
                            Tld = ".cn",
                            WikiDataId = "Q148"
                        },
                        new
                        {
                            Id = 21,
                            Capital = "Moscow",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "RUB",
                            CurrencyName = "Russian Ruble",
                            CurrencySymbol = "₽",
                            DeclarationOfIndependence = new DateOnly(1991, 12, 25),
                            Emoji = "🇷🇺",
                            EmojiU = "U+1F1F7 U+1F1FA",
                            IsMonarchy = false,
                            Iso2 = "RU",
                            Iso3 = "RUS",
                            Latitude = 55.755800000000001,
                            Longitude = 37.6173,
                            Name = "Russia",
                            Nationality = "Russian",
                            Native = "Россия",
                            NumericCode = "643",
                            PhoneCode = "7",
                            Tld = ".ru",
                            WikiDataId = "Q159"
                        },
                        new
                        {
                            Id = 22,
                            Capital = "Buenos Aires",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "ARS",
                            CurrencyName = "Argentine Peso",
                            CurrencySymbol = "$",
                            DeclarationOfIndependence = new DateOnly(1816, 7, 9),
                            Emoji = "🇦🇷",
                            EmojiU = "U+1F1E6 U+1F1F7",
                            IsMonarchy = false,
                            Iso2 = "AR",
                            Iso3 = "ARG",
                            Latitude = -34.603700000000003,
                            Longitude = -58.381599999999999,
                            Name = "Argentina",
                            Nationality = "Argentinian",
                            Native = "Argentina",
                            NumericCode = "032",
                            PhoneCode = "54",
                            Tld = ".ar",
                            WikiDataId = "Q414"
                        },
                        new
                        {
                            Id = 23,
                            Capital = "Seoul",
                            CreatedDate = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "KRW",
                            CurrencyName = "South Korean Won",
                            CurrencySymbol = "₩",
                            DeclarationOfIndependence = new DateOnly(1948, 8, 15),
                            Emoji = "🇰🇷",
                            EmojiU = "U+1F1F0 U+1F1F7",
                            IsMonarchy = false,
                            Iso2 = "KR",
                            Iso3 = "KOR",
                            Latitude = 37.566499999999998,
                            Longitude = 126.97799999999999,
                            Name = "South Korea",
                            Nationality = "South Korean",
                            Native = "대한민국",
                            NumericCode = "410",
                            PhoneCode = "82",
                            Tld = ".kr",
                            WikiDataId = "Q884"
                        });
                });

            modelBuilder.Entity("World.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Europe",
                            WikiDataId = "Q46"
                        },
                        new
                        {
                            Id = 2,
                            Name = "North America",
                            WikiDataId = "Q49"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asia",
                            WikiDataId = "Q48"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oceania",
                            WikiDataId = "Q538"
                        },
                        new
                        {
                            Id = 5,
                            Name = "South America",
                            WikiDataId = "Q18"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Africa",
                            WikiDataId = "Q15"
                        });
                });

            modelBuilder.Entity("World.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FipsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iso2")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Brussels-Capital"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Île-de-France"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "California"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 4,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 5,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Community of Madrid"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 6,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 7,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Tokyo Metropolis"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 8,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "New South Wales"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 9,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 10,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Greater London"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 11,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Ontario"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 12,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Western Cape"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 13,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Delhi"
                        });
                });

            modelBuilder.Entity("World.Entities.SubRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("SubRegion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d92a1d17-ea43-4337-b443-741e74d9f2c1"),
                            Name = "Western Europe",
                            RegionId = 1,
                            WikiDataId = "Q27574"
                        },
                        new
                        {
                            Id = new Guid("ee99e4a6-df46-40ac-a4ed-72bf3b44fbba"),
                            Name = "Northern America",
                            RegionId = 2,
                            WikiDataId = "Q49"
                        },
                        new
                        {
                            Id = new Guid("bf3514e8-3509-43cc-80b6-b966a43e74ca"),
                            Name = "Southern Asia",
                            RegionId = 3,
                            WikiDataId = "Q46169"
                        },
                        new
                        {
                            Id = new Guid("cf0da940-7235-4b1d-a8e8-9f5bf827a033"),
                            Name = "Eastern Asia",
                            RegionId = 3,
                            WikiDataId = "Q4628"
                        },
                        new
                        {
                            Id = new Guid("601bd8dc-4908-4cee-8844-73792e32fd5e"),
                            Name = "Australia and New Zealand",
                            RegionId = 4,
                            WikiDataId = "Q538"
                        },
                        new
                        {
                            Id = new Guid("47ce3e8b-61bc-4806-9499-01594ba19f1e"),
                            Name = "South America",
                            RegionId = 5,
                            WikiDataId = "Q18"
                        },
                        new
                        {
                            Id = new Guid("cdeb1ec2-d13b-4359-9592-e36809ce3104"),
                            Name = "Southern Africa",
                            RegionId = 6,
                            WikiDataId = "Q824"
                        });
                });

            modelBuilder.Entity("World.Entities.City", b =>
                {
                    b.HasOne("World.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("World.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("World.Entities.State", b =>
                {
                    b.HasOne("World.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("World.Entities.SubRegion", b =>
                {
                    b.HasOne("World.Entities.Region", "Region")
                        .WithMany("SubRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("World.Entities.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("World.Entities.Region", b =>
                {
                    b.Navigation("SubRegions");
                });

            modelBuilder.Entity("World.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
